### PR TITLE
Fixes #200 ReadStreamSubscriber does not properly handle errors deliv…

### LINKED ISSUE #200: ReadStreamSubscriber does not properly handle errors delivered during subscribe
Version -- 3.7.1

There are several Rx chains which will trigger a call to `onError` on the downstream immediately during subscription.  When this happens with an instance of `ReadStreamSubscriber` there is no way to actually receive the error since any attempt to set the exception or end handlers results in an `IllegalStateException` (even if the stream is paused).

Consider the following JUnit test:

```
    @Test
    public void errorToReadStream() throws InterruptedException {
        Flowable<Object> errorFlowable = Flowable.error(new RuntimeException("This is my error"));
        ReadStream<Object> errorStream = ReadStreamSubscriber.asReadStream(errorFlowable, 
                java.util.function.Function.identity());
        CountDownLatch latch = new CountDownLatch(1);
        List<Throwable> errors = new ArrayList<>();
        errorStream.pause();
        errorStream.handler(obj -> {});
        errorStream.exceptionHandler(errors::add);
        errorStream.endHandler(aVoid -> {
            latch.countDown();
        });
        errorStream.resume();
        latch.await();
        Assert.assertFalse(errors.isEmpty());
    }
```

Currently this will fail when setting the exception handler.  Ideally it would be nice if on the resume the exception and then end handler's were called (to deliver the error).

### PR DESCRIPTION
**Pull request by flukschander**
Motivation:

Currently in ReadStreamSubscriber#asReadStream the given Observable/Flowable is directly subscribed to which leads to an IllegalStateException should it only deliver an exception or is empty.
This change will subscribe to the give Observable/Flowable only on a call to ReadStreamSubscriber#handler which also conforms better to the ReadStream specification as it should only start to deliver elements as a handler is set.

### CODE REVIEW

**Comment by vietj** [comment]
we need to have tests for this

**Comment by flukschander** [comment]
> we need to have tests for this

Sorry for that. Added a few tests

**Comment by flukschander** [comment]
@vietj did you have time to review yet?

**Comment by vietj** [comment]
not yet, but it's on my todo list :-)

File: rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java [hunk 1]
```diff
@@ -57,6 +62,9 @@ public ReadStreamSubscriber(Function<R, J> adapter) {
     synchronized (this) {
       elementHandler = handler;
     }
+    Consumer<Subscriber<R>> action = execOnHandler;
+    execOnHandler = s -> {};
```
Comment (vietj) [inline rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java:66]: this swap should be done within the synchronized block

File: rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/ReadStreamSubscriber.java [hunk 2]
```diff
@@ -54,16 +53,26 @@
...
     this.adapter = adapter;
+    this.execOnHandler = execOnHandler;
   }
 
   @Override
   public ReadStream<J> handler(Handler<J> handler) {
     synchronized (this) {
       elementHandler = handler;
     }
+    Consumer<Subscriber<R>> action = execOnHandler;
```
Comment (vietj) [inline rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/ReadStreamSubscriber.java:73]: should be done within the synchronized block

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java [hunk 3]
```diff
@@ -54,16 +54,26 @@
...
+    this.execOnHandler = execOnHandler;
   }
 
   @Override
   public ReadStream<J> handler(Handler<J> handler) {
     synchronized (this) {
       elementHandler = handler;
     }
+    Consumer<Subscriber<R>> action = execOnHandler;
+    execOnHandler = s -> {};
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java:75]: should be done in the synchronized block

**Review by vietj — CHANGES_REQUESTED** [review]
minor change with respect to synchronization

**Comment by flukschander** [comment]
fixed as requested

File: rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java (hunk 1 above)
Comment (vietj) [reply rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java:66]: here also

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java (hunk 3 above)
Comment (vietj) [reply rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java:75]: here also

**Review by vietj — COMMENTED** [review]
more swap under sync

**Comment by flukschander** [comment]
done

**Comment by vietj** [comment]
can you provide a backport PR to 4.1 branch @flukschander ?
