### PR TITLE
WriteStream as RxJava subscriber

### LINKED ISSUE #115: Expose WriteStream as Observer
Following the vertx rx-java 2 documentation, it seems there's a easy way to transform a read stream into a flowable, using the `FlowableHelper.toFlowable` utility method, but **nothing for write streams**.

The documentation uses the following example to send data from rx-java to the eventbus:
```
observable.
    buffer(1, TimeUnit.SECONDS).
    map(samples -> samples.
        stream().
        collect(Collectors.averagingDouble(d -> d))).
    subscribe(heat -> {
      vertx.eventBus().send("news-feed", "Current heat is " + heat);
    });
```

But if you send messages to the eventbus in the `subscribe` method, you cannot handle backpressure correctly (I've an example that hangs if I send too many messages, but I don't get any exception to confirm that backpressure is the only problem).

Is there a way to turn a write stream into a `Observer`?
E.g.:
```
Observer<X> obs = FlowableHelper.toObserver(vertx.eventBus().publisher("address"));
observable.subscribe(obs);
```

Or something similar..

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #115

This pull request adds adapters for WriteStream:
- RxJava1 subscriber
- RxJava2 subscriber (Flowable)
- RxJava2 observable (Observable)

Also, rxified(generated) WriteStream objects get new methods:
- toSubscriber (RxJava1 and RxJava2)
- toObserver (RxJava2)

### CODE REVIEW

**Comment by tsegismont** [comment]
If this gets merged, we could close the Pump issue (#123) as wontfix.

**Comment by tsegismont** [comment]
@jponge @vietj @cescoffier for now it's missing docs/Javadoc, but it's planned.

**Comment by jponge** [comment]
Great PR!

Naive question: why requesting 256 items initially? Or 512, or 16, etc 😉

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+    this.writeStream = writeStream;
+    this.adapter = adapter;
+    this.onError = onError;
+    this.onComplete = onComplete;
+  }
+
+  @Override
+  public void onSubscribe(Subscription subscription) {
+    this.subscription = subscription;
+    subscription.request(256);
```
[the remark this answers is not in the document]
Comment (tsegismont) [reply rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java]: Which default? Which buffer is kept full?

**Comment by tsegismont** [comment]
> Naive question: why requesting 256 items initially? Or 512, or 16, etc wink

@jponge precisely because this is a naive implementation :smile: 

I'm fine with revisiting it after CR2 or in 3.6.1. At least for now I believe the feature should get to 3.6 and we can tune later

**Comment by jponge** [comment]
Ok that answers my question ;-)

**Comment by tsegismont** [comment]
>in code generator use writer.format instead of writer.write when you need to write variables

Ok, I followed the style of the existing code (`format` is not used in the project afaics)

**Comment by vietj** [comment]
@tsegismont sure thing, it should be, to have code more concise, so just do it for what you added

**Comment by tsegismont** [comment]
@vietj done

File: rx-java2-gen/src/main/java/io/vertx/reactivex/RxHelper.java [hunk 2]
```diff
@@ -65,4 +72,19 @@ public static Scheduler blockingScheduler(WorkerExecutor executor) {
     return new ContextScheduler(executor, false);
   }
 
+  public static <T> Subscriber<T> toSubscriber(WriteStream<T> stream, Consumer<Throwable> onError, Runnable onComplete) {
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/RxHelper.java]: javadoc ?

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+        if (drainHandlerSet) {
+          h = null;
+        } else {
+          drainHandlerSet = true;
+          h = v -> subscription.request(1);
+        }
+      }
+      if (h != null) {
+        writeStream.drainHandler(v -> {
+          synchronized (this) {
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java]: why can't this lambda be part of `h` created in the synchronised block ?

File: rx-java2-gen/src/main/java/io/vertx/reactivex/RxHelper.java (hunk 2 above)
Comment (tsegismont) [reply rx-java2-gen/src/main/java/io/vertx/reactivex/RxHelper.java]: Yeah, in the email to `vertx-dev` I said docs were planned but I wanted to share the code early.

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java (hunk 3 above)
Comment (tsegismont) [reply rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java]: To minimize actions in the synchronized block.

Comment (vietj) [reply rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java]: this is actually a lambda capture and not execute. The lambda will be actually called by the drain handler, so there isn't more less work done and actually is it less performant because it will instantiate two lambdas instead of one.

Comment (vietj) [reply rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java]: actually this lambda could even been created once because it's not capturing anything from the local scope and only updates the object fields.

**Comment by tsegismont** [comment]
@vietj @jponge @cescoffier please take another look

Here's what I did after the initial push:

- make sure RxJava2 subscriber/observer conform to the reactive streams protocol
- less naive backpressure management (request elements in batches)
- handle WriteStream errors

It might be easier to review commits one after the other.

My last planned changes are docs.

File: rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+import java.util.Objects;
+import java.util.function.Consumer;
+import java.util.function.Function;
+
+/**
+ * @author Thomas Segismont
+ */
+public class WriteStreamSubscriber<R, T> extends Subscriber<R> {
+
+  private static final int BATCH_SIZE = 256;
```
Comment (vietj) [inline rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java]: 256 is a lot, we rather want to use 16

File: rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+  public WriteStreamSubscriber(WriteStream<T> writeStream, Function<R, T> adapter, Consumer<Throwable> onError, Runnable onComplete) {
+    Objects.requireNonNull(writeStream, "writeStream");
+    Objects.requireNonNull(adapter, "adapter");
+    Objects.requireNonNull(onError, "onError");
+    Objects.requireNonNull(onComplete, "onComplete");
+    this.writeStream = writeStream;
+    this.adapter = adapter;
+    this.onError = onError;
+    this.onComplete = onComplete;
+    this.drainHandler = v -> {
```
Comment (vietj) [inline rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java]: rather do that using a method called by the lambda for better readability

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java [hunk 6]
```diff
@@ -0,0 +1,196 @@
...
+    synchronized (this) {
+      if (done || outstanding > 0) {
+        return;
+      }
+      outstanding = BATCH_SIZE;
+    }
+    s.request(BATCH_SIZE);
+  }
+
+  private synchronized boolean switchDrainHandlerSetOn() {
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriber.java]: what's the point if that's used only once ? rather inline it

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamObserver.java [hunk 7]
```diff
@@ -0,0 +1,152 @@
...
+
+  @Override
+  public void onSubscribe(Disposable disposable) {
+    Objects.requireNonNull(disposable, "disposable");
+    if (!setDisposable(disposable)) {
+      disposable.dispose();
+      DisposableHelper.reportDisposableSet();
+    }
+    writeStream.exceptionHandler(t -> {
+      getDisposable().dispose();
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamObserver.java]: why not use the `disposable` method argument ?

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamObserver.java [hunk 8]
```diff
@@ -0,0 +1,152 @@
...
+    this.onError = onError;
+    this.onComplete = onComplete;
+  }
+
+  @Override
+  public void onSubscribe(Disposable disposable) {
+    Objects.requireNonNull(disposable, "disposable");
+    if (!setDisposable(disposable)) {
+      disposable.dispose();
+      DisposableHelper.reportDisposableSet();
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamObserver.java]: shouldn't we return in this block ?

File: rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java (hunk 5 above)
Comment (tsegismont) [reply rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java]: Agreed

File: rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamObserver.java (hunk 7 above)
Comment (tsegismont) [reply rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamObserver.java]: Because it's guarded by the `WriteStreamObserver` instance and using it like this makes the code more readable, I think.

**Comment by tsegismont** [comment]
I have just pushed the documentation for this.

I discussed the implementation off-list with @vietj . His main concern is about using this on non-Vert.x threads (possible race condition with `isWriteQueueFull` and `drainHandler` invocation). I change #115 milestone to `3.6.1` so we should have some time to look into this.

@jponge @cescoffier I would appreciate if you find a few cycles to take a look at the documentation/API.

File: rx-java/src/main/asciidoc/vertx-rx/java/index.adoc [hunk 9]
```diff
@@ -89,6 +89,45 @@ an `rx.Observable` to a Vert.x read stream:
 {@link examples.NativeExamples#toReadStream}
 ----
 
+=== Write stream support
+
+A {@link io.vertx.core.streams.WriteStream}, like a `rx.Subscriber`, consumes items and collaborates with producers to avoid overflows.
```
Comment (jponge) [inline rx-java/src/main/asciidoc/vertx-rx/java/index.adoc]: Perhaps say _to avoid unbounded pending write queue_ or something like this more specific.

Comment (tsegismont) [reply rx-java/src/main/asciidoc/vertx-rx/java/index.adoc]: I went with:

```
A {@link io.vertx.core.streams.WriteStream}, like a `rx.Subscriber`, consumes items, and, when it can't keep-up, collaborates with the producer to avoid an ever-growing backlog.
```

I hope it's clear enough.

**Comment by jponge** [comment]
Spot on!

**Comment by tsegismont** [comment]
@vietj I've rebased on `master` and pushed a fix to avoid races with (`drainHandler`/`writeQueueFull`)

**Comment by tsegismont** [comment]
Sorry, must have happened when I rebased the PR and merged the conflicts
with the 4.0 changes

**Comment by tsegismont** [comment]
@vietj done

**Comment by vietj** [comment]
do we really need to add new API types ? (WriteStreamObserver/WriteStreamSubscriber)

**Comment by tsegismont** [comment]
@vietj it's not absolutely necessary. The callbacks can be provided in the `toSubscriber`/`toObserver` methods. This other option looked less convenient to me.

**Comment by vietj** [comment]
I prefer to minimize the surface area of this API as it might evolve in the future.

File: rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+ * under the License.
+ */
+
+package io.vertx.rx.java;
+
+import io.vertx.core.Handler;
+import rx.Subscriber;
+
+/**
+ * A {@link io.vertx.core.streams.WriteStream} to {@link Subscriber} adpater.
```
Comment (vietj) [inline rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java]: typo

File: rx-java2-gen/src/main/java/io/vertx/reactivex/WriteStreamObserver.java [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+ * under the License.
+ */
+
+package io.vertx.reactivex;
+
+import io.reactivex.Observer;
+import io.vertx.core.Handler;
+
+/**
+ * A {@link io.vertx.core.streams.WriteStream} to {@link Observer} adpater.
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/WriteStreamObserver.java]: typo

File: rx-java2-gen/src/main/java/io/vertx/reactivex/WriteStreamSubscriber.java [hunk 12]
```diff
@@ -0,0 +1,55 @@
...
+ * under the License.
+ */
+
+package io.vertx.reactivex;
+
+import io.reactivex.FlowableSubscriber;
+import io.vertx.core.Handler;
+
+/**
+ * A {@link io.vertx.core.streams.WriteStream} to {@link org.reactivestreams.Subscriber} adpater.
```
Comment (vietj) [inline rx-java2-gen/src/main/java/io/vertx/reactivex/WriteStreamSubscriber.java]: typo

**Comment by vietj** [comment]
why are the example using the RxHelper instead of the generated API ? this force to use un-rxified API which needs to use FQN types which are clutters the readability

**Comment by vietj** [comment]
the WriteStreamSubscriber etc... should offer an homogeneous callback API. Now it mixes Rxjava style (Runnable) and Vertx style (Handler<Throwable>), I believe as it should either use Handler<Void> or RxJava Consumer.

File: rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java (hunk 10 above)
Comment (tsegismont) [reply rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java]: where's the typo?

**Comment by tsegismont** [comment]
> why are the example using the RxHelper instead of the generated API ? this force to use un-rxified API which needs to use FQN types which are clutters the readability

Agreed. I can go move the paragraph about the Rxified API near the top and then continue with Rxified API examples only. Fine with you?

**Comment by tsegismont** [comment]
>the WriteStreamSubscriber etc... should offer an homogeneous callback API. Now it mixes Rxjava style (Runnable) and Vertx style (Handler), I believe as it should either use Handler or RxJava Consumer.

Right. I'll switch  to an RxJava-like API

**Comment by vietj** [comment]
adpater

**Comment by vietj** [comment]
yes

**Comment by vietj** [comment]
thanks

**Comment by tsegismont** [comment]
@vietj I just pushed 3 commits w/ the requested changes

**Comment by vietj** [comment]
looks good, can you squash commits when merging to facilitate back-port to 3.6 ?

**Comment by tsegismont** [comment]
Sure, will do.
